Fixed Error in example pubspec and Removed ? from WidgetsBinding
jaumard/infinite_widgets pull request #2
Opened 2022-06-14 19:40 UTC by jabguru

The package shows an error in Flutter 3.0 because of the null aware operator on WidgetsBinding.instance.
Also, I fixed the error shown by linter in pubspec.yaml for the example.

2022-06-14 21:03 UTC, jaumard requested changes
Hey thanks for the PR! 
Few little changes needed please

2022-06-14 21:03 UTC, jaumard commented on example/ios/Flutter/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
Shouldn't be here, can you please remove it

2022-06-15 05:07 UTC, jaumard commented on example/ios/Flutter/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
I was able to do it myself all good :)

2022-06-15 05:08 UTC, merged

2022-06-15 12:24 UTC, jabguru commented
Thanks!